# Site settings
title: Ashkan Blog
email: ashkanx@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ashkanx.com" # the base hostname & protocol for your site
twitter_username: ashkanxx
github_username:  ashkanx

# Build settings
markdown: kramdown
paginate: 5

collections:
  main-en:
    output: true
    permalink: /en/:path/
  main-ru:
    output: true
    permalink: /ru/:path/
