# Site settings
title: Ashkan Blog
email: ashkanx@outlook.com
description:  I write about whatever I find interesting!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ashkanx.com" # the base hostname & protocol for your site
twitter_username: ashkanxx
github_username:  ashkanx

# Build settings
markdown: kramdown
paginate: 5
#conversion
excerpt_separator:"\n\n"
paginate_path: "page:num"

collections:
  main-en:
    output: true
    permalink: /en/:path/
  main-ru:
    output: true
    permalink: /ru/:path/
